services:
  - type: web
    name: namma-bites-backend
    env: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: namma-bites-redis
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: VITE_API_URL
        value: /api
  - type: redis
    name: namma-bites-redis
    ipAllowList: []

